apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thawatchai-rvc/k3s-gitops.git
    targetRevision: HEAD
    # path: apps/01-web-nginx
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
